#config/database.yml
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: time_to_answer_development
  username: postgres
  password: 123456
  host: localhost

test:
  <<: *default
  database: time_to_answer_test
  username: postgres
  password: 123456
  host: localhost
